application: musicviz194
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /src/app
  static_dir: src/app
- url: /css
  static_dir: .tmp/css
- url: /bower_components
  static_dir: bower_components
- url: /common
  static_dir: src/app/common
- url: /home
  static_dir: src/app/home
- url: /queue
  static_dir: src/app/queue
- url: /search
  static_dir: src/app/search
- url: /app.js
  static_files: src/app/app.js
  upload: src/files/app.js
- url: /jukebox-templates.js
  static_files: .tmp/jukebox-templates.js
  upload: .tmp/jukebox-templates.js
- url: /api
  script: handler.application
  login: admin
  secure: always
- url: /api/.*
  script: handler.application
- url: .*
  static_files: src/app/index.html
  upload: src/app/index.html
# - url: /dist
#   static_dir: dist
# - url: .*
#   static_files: dist/index.html
#   upload: dist/index.html


builtins:
- deferred: on
- remote_api: on

skip_files: # TODO: flesh this out
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^app$
- ^node_modules$
- ^bower_components$
# - ^src$ # TODO: figure out why this needs to be included
