application: musicviz194
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /src/app
  static_dir: src/app
- url: /css
  static_dir: .tmp/css
- url: /angular
  static_dir: bower_components/angular
- url: /angular-bootstrap
  static_dir: bower_components/angular-bootstrap
- url: /angular-route
  static_dir: bower_components/angular-route
- url: /angular-mocks
  static_dir: bower_components/angular-mocks
- url: /angular-ui
  static_dir: bower_components/angular-ui
- url: /angular-ui/build
  static_dir: bower_components/angular-ui/build
- url: /bootstrap
  static_dir: bower_components/bootstrap
- url: /jquery
  static_dir: bower_components/jquery
- url: /jquery-ui
  static_dir: bower_components/jquery-ui
- url: /normalize-css
  static_dir: bower_components/normalize-css
- url: /common
  static_dir: src/app/common
- url: /queue
  static_dir: src/app/queue
- url: /search
  static_dir: src/app/search
- url: /todo
  static_dir: src/app/todo # remove this later
- url: /app.js
  static_files: src/app/app.js
  upload: src/files/app.js
- url: /jukebox-templates.js
  static_files: .tmp/jukebox-templates.js
  upload: .tmp/jukebox-templates.js
- url: /api
  script: handler.application
- url: /api/.*
  script: handler.application
- url: .*
  static_files: src/app/index.html
  upload: src/app/index.html


builtins:
- deferred: on

skip_files: # TODO: flesh this out
#- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^app$
- ^node_modules$
